INSERT INTO USER(ID, FIRST_NAME, LAST_NAME, COMPANY_NAME)
VALUES (1, 'ADAM', 'DALIGOWSKI', 'PZU');
INSERT INTO USER(ID, FIRST_NAME, LAST_NAME, COMPANY_NAME)
VALUES (2, 'ŁUKASZ', 'CIESIELSKI', 'MBANK');
INSERT INTO USER (ID, FIRST_NAME, LAST_NAME, COMPANY_NAME)
VALUES (3, 'MARCIN', 'GŁOWACKI', 'NETIA');